### ISSUE TITLE
right_sidebar! can not be collapsed

### ISSUE THREAD

**Issue by fabrouy** [activeadmin-plugins/active_admin_sidebar#12]
https://github.com/activeadmin-plugins/active_admin_sidebar/blob/master/lib/active_admin_sidebar/positions.rb#L14

Why does it not accept options like his left brother? :)

**Comment by Fivell** [comment]
@Moriort  @fabrouy  this option is missing and so was never tested , feel free to contribute

**Comment by workgena** [comment]
We never thought about it because of HTML layout of ActiveAdmin.

Basically when index#table is to large, then it pushes away the Right-sidebar. So the "hide button" does not needed, because it behave like "auto hide" (to see it you need to scroll page horizontally).

Close for now.
