### ISSUE TITLE
latest stable version on rubygems is 0.0.5

### ISSUE THREAD

**Issue by tmaybe** [activeadmin-plugins/active_admin_sidebar#14]
Hi, I'm interested in using this plugins as a gem in my project. I notice that the most recent version on rubygems is 0.0.5, but that you're up to 1.0.0 here in the repo.

Is there anything I can contribute to help get 1.0.0 up on rubygems?

**Comment by Fivell** [comment]
@tmaybe released https://rubygems.org/gems/active_admin_sidebar/versions/1.0.0

**Comment by tmaybe** [comment]
🙌 thanks!
