### ISSUE TITLE
undefined local variable or method `build_sidebar' for #<ActiveAdmin::Views::Pages::Index:0x00007f8ae8961a48> Did you mean?  build_head

### ISSUE THREAD

**Issue by peacejet** [activeadmin-plugins/active_admin_sidebar#15]
Hello. Thank you for making this gem. 
However, in my environment it was impossible to move without trouble. The content of the error was **"undefined local variable or method `build_sidebar 'for # <ActiveAdmin :: Views :: Pages :: Index: 0x00007f8ae8961a48> Did you mean?
Build_head."**

Perhaps written in the "build_page_content" method in the library file.
I changed the **"build_sidebar"** to **"sidebar sidebar_sections_for_action"** and it was confirmed that it works.
 I am not confident, but I'm glad if you can check and fix it.

Thank you.

**Comment by workgena** [comment]
Please, provide your Rails and ActiveAdmin versions.

**Comment by varyonic** [comment]
Probably related to  https://github.com/activeadmin/activeadmin/commit/bd34a9ef51003e204074a902f7fe14a53eabd585

**Comment by workgena** [comment]
Oh, ty. I'll take a look at this change.

**Comment by peacejet** [comment]
Hi. @varyonic Thank you so much. I also see that commitment. @workgena I'm glad if it helped you in some way.

**Comment by workgena** [comment]
@peacejet Fixed the issue. You can take fresh version from master branch.
We will push the release version to the RubyGems later, when ActiveAdmin 1.4 come out.

**Comment by peacejet** [comment]
@workgena I confirmed the behavior of the modified code. Thank you for updating.
> We will push the release version to the RubyGems later, when ActiveAdmin 1.4 come out.
I got it. thanks!

**Comment by workgena** [comment]
Latest v1.1.0 now available on [RubyGems](https://rubygems.org/gems/active_admin_sidebar), it is compatible with ActiveAdmin 1.4.0
