### ISSUE TITLE
File to import not found or unreadable: active_admin_sidebar

### ISSUE THREAD

**Issue by waleedarshad** [activeadmin-plugins/active_admin_sidebar#7]
Active admin side bar is not working activeadmin 1.0.0.pre2

**Comment by Fivell** [comment]
@waleedarshad , what version of active_admin_sidebar are you trying to use?

**Comment by waleedarshad** [comment]
@Fivell active_admin_sidebar 0.0.5

**Comment by Fivell** [comment]
@waleedarshad . "0.1.0.rc3" should work with AA 1+

**Comment by waleedarshad** [comment]
@Fivell Thanks

**Comment by waleedarshad** [comment]
Well i have write scss myself. but will try in future if requirements come again.
